### ISSUE TITLE
Enable hierarchical planning with issues on GitHub

### ISSUE THREAD

**Issue by ase19410008** [ase19410008/test-issue#5]
Overview

Issues can be nested in task lists of other issues as a new way to group work related to the same theme,
feature, or objective. This new directional relationship will include additional experiences that make it easier
to follow progress, discuss product changes, and track ideas at a higher level of fidelity.

Intended Outcome
Help teams organize and track their issue based on the goals or thematic outcomes they want to achieve.

Features
- [x] Improve the MD editing experience to speed up task creation #736
- [x] Create directional relationships between two issues #737
- [x] Show progress and parent information on the issue page #738
- [x] Convert text into issues #739
- [ ] Keep issue state and checkboxes in sync #740
- [ ] Add delight to the experience when all tasks are complate

References
Design wireframes
Research report
Previous explorations
